# Coursera Data Science Specialization
---
- hosts: 127.0.0.1
  sudo: yes
  connection: local
  tasks:
    - name: Install SQLite
      apt: pkg={{item}} state=latest
      with_items:
        - sqlite3
        - libsqlite3-dev
    - name: Install MongoDB
      apt: pkg=mongodb state=latest
    - name: Create /data/db/ directory for MongoDB
      file: path=/data/db state=directory owner={{dst_username}} group={{dst_username}}
    - name: Install Chromium
      apt: pkg=chromium-browser state=latest
    - name: Install RStudio dependencies
      apt: pkg={{item}} state=latest
      with_items:
        - libjpeg62
        - gstreamer0.10-plugins-base
    - name: Download RStudio
      get_url: url=http://download1.rstudio.org/rstudio-0.98.507-amd64.deb dest=/tmp/rstudio.deb
    - name: Install RStudio
      shell: dpkg -i /tmp/rstudio.deb
